spring:
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: DeliveryAggregator
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=delivery_aggregator
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:db_changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=delivery_aggregator
    user: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxnatasha03@gmail.com
    password: arivofgxrqoubmek
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
authorization-codes:
  cdek:
    client-id: wqGwiQx0gg8mLtiEKsUinjVSICCjtTEP
    client-secret: RmAmgvSgSl1yirlz9QupbzOJVqhCxcP5
  yandex: y2_AgAAAAD04omrAAAPeAAAAAACRpC94Qk6Z5rUTgOcTgYFECJllXYKFx8
  dpd:
    client-number: 1001027795
    client-key: 182A17BD6FC5557D1FCA30FA1D56593EB21AEF88